- name: Get OSPF state and print
  hosts: routers
  gather_facts: false
  tasks:
  - name: Get OSPF neighbor state
    ansible.utils.cli_parse:
      command: "show ip ospf neighbor"
      parser:
        name: ansible.netcommon.pyats
      set_fact: ospf_parsed
  - name: print output parsed
    ansible.builtin.debug:
      var: ospf_parsed

